Wisdomb33r/ffch-admin

src/app/app.component.html
src/app/app.module.ts
src/app/ffbe/characters/characters.component.html
src/app/ffbe/characters/characters.component.ts
src/app/ffbe/ffbe.module.ts
src/app/ffbe/model/character.model.ts
src/assets/units.json

Adding a route to character component.
Creating a very simple form to enter character name.
Adding a very reduced JSON file containing real units for testing.

First step, let user enter the name of the character they want to import

---

.gitignore
package.json

Adding dist folder to ignore list.

Setting base-href parameter for prod build.

---

package-lock.json
src/app/ffbe/unit-awakening-materials-display/unit-awakening-materials-display.component.html

"Matériaux d'éveil" was displayed twice for unit awakenings.

Removed duplicated title

---

src/app/ffbe/mappers/latent-skill-mapper.ts
src/app/ffbe/model/latent-skill.model.ts
src/app/ffbe/services/latent-skills.service.ts

The mapper was considering "parent" LatentSkill to create the Amelioration, so that the EP cost was wrong.

Fixed the mapping of LatentSkill into Amelioration

---

src/app/ffbe/mappers/effects/abilities/ability-skill-modifier-increase.parser.ts

Prevent skill mod increase parser to hide 0% values

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-single-ally-covers.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-single-ally-covers.parser.ts

This was the missing parser for Aloha Lasswell.

Fixes #63: Added the AbilitySingleAllyCoversParser

---

src/app/ffbe/mappers/effects/abilities/ability-death-infliction.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-death-infliction.parser.ts
src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts

This parser is needed for Grim Lord Sakura and Kryla.

#66: Added the AbilityDeathInflictionParser

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-lb-damage-increase.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-lb-damage-increase.parser.ts

This was the missing parser for Christine.

Fixes #64: Added the AbilityLbDamageIncreaseParser

---

src/app/ffbe/mappers/effects/abilities/ability-barriers.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-barriers.parser.ts
src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts

This parser is needed for Grim Lord Sakura.

#66: Added the AbilityBarriersParser

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-enemy-scan.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-enemy-scan.parser.ts

This parser was missing for Kryla.

#65: Added the AbilityEnemyScanParser

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-spell-nullification.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-spell-nullification.parser.ts

This parser was missing for Kryla.

#65: Added the AbilitySpellNullificationParser

---

src/app/ffbe/mappers/effects/abilities/ability-berserk-infliction.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-berserk-infliction.parser.ts
src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts

This parser is required for Karten.

Fixes #90: Added the AbilityBerserkInflictionParser

---

src/app/ffbe/mappers/effects/abilities/ability-damages-hybrid.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-damages-hybrid.parser.ts

Fixing hybrid damages mod calculation (#87).

---

src/app/ffbe/mappers/effects/abilities/ability-damages-fixed.parser.ts
src/app/ffbe/mappers/effects/effect-parser.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts

Fixing stats list by identifier for physical mitigation and damages to undead

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-random-skills.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-random-skills.parser.ts

Fixes #68: Added the AbilityRandomSkillsParser

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-stats-increase.parser.ts

Stats increase now has wording for passive critical hit chance of normal attacks

---

src/app/ffbe/character-equipments-display/character-equipments-display.component.html
src/app/ffbe/character-skill-display/character-skill-display.component.html
src/app/ffbe/enhancement-display/enhancement-display.component.html
src/app/ffbe/formule-display/formule-display.component.html
src/app/ffbe/mappers/effects/abilities/ability-berserk-infliction.parser.ts
src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-normal-attack-modifier-increase.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-normal-attack-modifier-increase.parser.ts
src/app/ffbe/objet-display/objet-display.component.html
src/app/ffbe/recette-display/recette-display.component.html
src/app/ffbe/unit-display/unit-display.component.html

Ability normal attack power increase parser (#85).

---

src/app/ffbe/mappers/effects/effect-parser.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-skill-alive-ally-activation.parser.ts
src/app/ffbe/skills/skills.component.ts

Passive skill activation when an ally is alive extended to handle genre restrictions

---

src/app/ffbe/mappers/effects/abilities/ability-damages-dots.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-damages-dots.parser.ts

Fixing DOTs parser to handle magic damages scaling on SPR (#126).

---

src/app/ffbe/mappers/effects/passives/passive-skill-modifier-increase.parser.ts

Passive skill modifier increase now properly rounded to the closer integer

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-magic-multiple-activation.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-magic-multiple-activation.parser.ts

Ability magic multiple activation parser (#127).

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-item-steal.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-item-steal.parser.ts

Item steal parser (#138).

---

src/app/ffbe/mappers/effects/abilities/ability-death-infliction.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-death-infliction.parser.ts

Bugfixing a parameter analysis error on death inflict parser (#141).

---

src/app/ffbe/mappers/effects/abilities/ability-dispels.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-enemy-scan.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-stop-infliction.parser.spec.ts
src/app/ffbe/mappers/effects/effect-parser.ts

Now parsing correctly target for all allies and all enemies (#140).

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-magic-reflect.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-magic-reflect.parser.ts

Magic reflect parser (#134).

---

src/app/ffbe/mappers/effects/abilities/ability-skill-modifier-increase.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-skill-modifier-increase.parser.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-skill-modifier-increase.parser.ts
src/app/ffbe/model/skill.model.ts

Healing mod increase calculation (#139).

---

package.json
sonar-project.properties
src/app/ffbe/mappers/effects/abilities/ability-debuffs-steal.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-debuffs-steal.parser.ts

Improving french wording for debuffs steal parser.

---

src/app/ffbe/mappers/effects/effect-parser.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts

This effect is provided by Operative Zyrus' skill 913459 (Encrypted Code).

#156: Added the general mitigation to the effects list

---

package.json
sonar-project.properties
src/app/ffbe/mappers/effects/abilities/ability-skill-multiple-activation.parser.ts
src/app/ffbe/mappers/effects/abilities/ability-stats-modification.parser.ts

Standardizing wording for skill activation (#171).

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-skill-multiple-activation.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-skill-multiple-activation.parser.ts

GLEX parser for multi skill (#172).

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-healing-percent.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-healing-percent.parser.ts

Healing percent with self sacrifice parser (#182).

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.ts
src/app/ffbe/mappers/effects/passives/passive-stats-increase-hp-threshold.parser.ts

GLEX passive HP threshold stats increase parser (#181).

---

src/app/ffbe/mappers/effects/abilities/ability-skill-modifier-increase.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-skill-modifier-increase.parser.ts

Correcting wrong duration plural form in skill modifier increase

---

src/app/ffbe/mappers/consumable-mapper.spec.ts
src/app/ffbe/mappers/consumable-mapper.ts
src/app/ffbe/mappers/equipment-mapper.spec.ts
src/app/ffbe/mappers/equipment-mapper.ts
src/app/ffbe/mappers/materia-mapper.spec.ts
src/app/ffbe/mappers/materia-mapper.ts
src/app/ffbe/model/consumable.model.spec.ts

Fallback to object long description if short is missing

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.ts
src/app/ffbe/mappers/effects/passives/passive-mp-absorb.parser.ts

MP absorb when taking magic damages parser (#173).

---

src/app/ffbe/mappers/effects/effect-parser.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-stats-increase-hp-threshold.parser.ts

Improving HP/MP recovery wording on HP threshold parser (#174).

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-skill-multiple-activation.parser.ts

Passive multi-cast parser can now handle distinct multi-skills (#178).

---

src/app/ffbe/mappers/effects/abilities/ability-effect-parser.factory.ts
src/app/ffbe/mappers/effects/abilities/ability-mag-increase-next-action.parser.spec.ts
src/app/ffbe/mappers/effects/abilities/ability-mag-increase-next-action.parser.ts

Ability mag increase for next action parser (#191).

---

src/app/ffbe/ffbe.constants.ts

Added FFX-2, FFXIII-2 and FMA: Brotherhood

#202: Added missing games

---

src/app/ffbe/objet-alterations-etat-display/objet-alterations-etat-display.component.html

#208: Fixed a wrong name in a status ailment entry

---

src/app/ffbe/mappers/effects/abilities/ability-debuffs-resistance.parser.ts

#213: Missing case in the AbilityDebuffResitanceParser

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.ts
src/app/ffbe/mappers/effects/passives/passive-ailments-cure-after-battle.parser.ts

This parses the passive abilities for curing status ailments after battle.

#207: Added the PassiveAilmentsCureAfterBattleParser

---

src/php/equipments.php
src/php/skill_awakenings.php
src/php/units.php

Correcting a backend code fatal exception raised during error handling

---

src/app/ffbe/ffbe.constants.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passives/passive-esper-summon-damage-increase.parser.ts

Only the case with a single esper was handled so far.

#193: Added bonus to summon damages provided by several espers

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/equipment-mapper.spec.ts
src/app/ffbe/mappers/equipment-mapper.ts
src/app/ffbe/model/equipment/equipment.model.ts
src/app/ffbe/objets-display/objets-display.component.ts
src/app/ffbe/services/characters.service.spec.ts

Equipment items requirements

---

src/app/ffbe/mappers/consumable-mapper.spec.ts
src/app/ffbe/model/effects/abilities/ability-skill-switch-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-skill-switch-effect.model.ts

Changing wording for switch skills to avoid pushing the enhanced version of the skill independently

---

src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-chain-base-modifier-increase-effect.model.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts

Base chaining modifier increase parser (#262).

---

src/app/ffbe/skill-display/skill-display.component.ts

Now always using gumi identifier to generate website skills links 

---

src/app/ffbe/mappers/character-entry-mapper.ts

Avoid reuse of skills objects for different unit ranks (#289).

---

src/php/classes.php
src/php/skill_awakenings.php

#296: Added gil cost of unit awakenings

---

src/app/ffbe/model/effects/abilities/ability-mitigation-monster-type-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-mitigation-monster-type-effect.model.ts

Fixes #302 
Yoshikiri introduced a new valid configuration.

#302: Updated validity check for parameters of AbilityMitigationMonsterTypeEffect

---

src/app/ffbe/model/skill.model.ts

Fixes #317 
This was forgotten.

#317: Added AbilityDamagePhysicalIncreasedBreakEffect to the list of effects dealing damages

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-increased-break-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-increased-break-effect.model.ts

in AbilityDamagePhysicalIncreasedBreakEffect, and wrote a test.
Fixes #320

#320: Implemented getDamagesPower()

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-increased-modifier-enemy-type-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-increased-modifier-enemy-type-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts
src/app/ffbe/model/skill.model.ts

Physical damages with increased modifier on specific enemy type parsing

---

src/app/ffbe/unit-awakening-materials-display/unit-awakening-materials-display.component.ts
src/php/unit_awakenings.php

... and updated the backend script.
Fixes #321

#321: Added the "obtainment" checkbox for 8-star units

---

src/app/ffbe/objets-display-components/objet-display/objet-display.component.html

#342: Fixed paths for images

---

package.json
sonar-project.properties
src/app/ffbe/mappers/character-entry-mapper.spec.ts
src/app/ffbe/mappers/character-entry-mapper.ts
src/app/ffbe/mappers/character-mapper.ts

Original commit ce7c7c97224b258f62418c61dc65df40c2db5b88
Fixes #347

#347: Competences are shared among units of the same character

---

src/app/ffbe/mappers/character-entry-mapper.ts
src/app/ffbe/model/limit-burst.model.ts
src/app/ffbe/services/data-mining-client.service.ts
src/app/ffbe/services/limit-bursts.service.spec.ts
src/app/ffbe/services/limit-bursts.service.ts

The DM contains a syntax error, and we no longer use these fields.

#365: Removed JSON parsing and display of LB descriptions

---

.gitignore
src/app/ffbe/item-recipes/item-recipes.component.ts
src/app/ffbe/recettes-display/recettes-display.component.ts

Character service injection to avoid a crash in recipes parsing (#361).

---

src/app/ffbe/model/effects/abilities/ability-zombie-cure-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-zombie-cure-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts

Zombie cure parsing (#362).

---

package.json
sonar-project.properties
src/app/ffbe/model/effects/abilities/ability-weapon-type-wielder-damage-increase-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-weapon-type-wielder-damage-increase-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts

Weapon type wielder damage increase parsing (#367).

---

package.json
sonar-project.properties
src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts
src/app/ffbe/model/effects/passives/stats/passive-equipment-stats-doublehand-shield-increase-effect.model.ts

Double hand with or without shield parser (#382).

---

src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-broken-target-damage-increase-effect.model.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts

Damage increase against broken ennemies parser

---

src/app/ffbe/mappers/character-entry-mapper.ts
src/app/ffbe/model/effects/abilities/skill/ability-skill-tag-team-attack-activation-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/skill/ability-skill-tag-team-attack-activation-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts
src/app/ffbe/model/limit-burst.model.ts
src/app/ffbe/services/limit-bursts.service.ts

Tag team attack activation parser

---

src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-skill-replacing-normal-attack-effect.model.spec.ts
src/app/ffbe/model/effects/passives/passive-skill-replacing-normal-attack-effect.model.ts

Skill replacing normal attacks parser

---

src/app/ffbe/character-display/character-display.component.html
src/app/ffbe/enhancement-display/enhancement-display.component.html
src/app/ffbe/mappers/character-mapper.ts

Fixes #388 
Also fixed the swapped French and English names in the Character constructor.

#388: Added character English name into Character and Enhancement Display components

---

src/app/ffbe/objets-display-components/objet-display/objet-display.component.html
src/app/ffbe/objets-display-components/objet-display/objet-display.component.ts

#387: Added button with FFCH link to Objet

---

src/app/ffbe/ffbe.module.ts
src/app/ffbe/skill-display/skill-display.component.css
src/app/ffbe/skill-display/skill-display.component.html
src/app/ffbe/skill-display/skill-display.component.ts
src/app/ffbe/unit-display/unit-display.component.css
src/app/ffbe/unit-display/unit-display.component.html
src/app/ffbe/unit-display/unit-display.component.ts
src/index.html

Allow switch to multi line effect edit

---

package.json
sonar-project.properties
src/app/ffbe/mappers/skill-mapper.spec.ts
src/app/ffbe/mappers/skill-mapper.ts

Abilities unit restrictions

---

src/app/ffbe/model/effects/abilities/ability-gil-steal-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-gil-steal-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts

Gil steal parsing

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-increased-break-effect.model.ts

Fixing wrong parameter in attack with increased BREAK damageparsing

---

src/php/skills.php

Remove old competence values when re-pushing

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-jump-delay-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-physical-jump-delay-effect.model.ts

Fixes #432  
There was an extra parameter that caused a parameter error.
Changed the non-critical parameters oddities into warning.

 #432: Fixed parameter error in AbilityDamagePhysicalJumpDelayEffect

---

src/app/ffbe/enhancement-display/enhancement-display.component.html
src/app/ffbe/enhancement-display/enhancement-display.component.ts
src/app/ffbe/items/items.component.ts
src/app/ffbe/mappers/items/equipment-mapper.spec.ts
src/app/ffbe/mappers/items/equipment-mapper.ts
src/app/ffbe/services/characters.service.spec.ts
src/app/ffbe/services/characters.service.ts
src/app/ffbe/services/skills.service.ts

 #439: Tentative improvement of Enhancements loading times

---

src/app/ffbe/model/effects/passives/passive-elements-resistance-effect.model.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts

Fixing an array length error while parsing passive elemental resistance parsing

---

src/app/ffbe/mappers/items/vision-card-mapper.ts

Mapping elemental resistances, killers and equipment stats augmentation from VC skills to VC item

---

package.json
sonar-project.properties
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts
src/app/ffbe/model/effects/passives/stats/passive-equipment-category-stats-increase-effect.model.ts

 #470: Fixed parameterError in PassiveEquipmentCategoryStatsIncreaseEffect

---

src/app/ffbe/mappers/character-entry-mapper.ts
src/app/ffbe/mappers/character-mapper.spec.ts

Defining special skill levels for EX+1, EX+2 and EX+3 obtention.

---

src/app/ffbe/characters/characters.component.ts
src/app/ffbe/enhancements/enhancements.component.ts
src/app/ffbe/latent-skills/latent-skills.component.ts
src/app/ffbe/mappers/skill-mapper.spec.ts
src/app/ffbe/mappers/skill-mapper.ts
src/app/ffbe/model/items/vision-cards/vision-card.model.spec.ts
src/app/ffbe/services/vision-cards.service.spec.ts
src/app/ffbe/skills/skills.component.ts

Equipment requirement for skill activation now also correct for Vision Cards

---

package.json
sonar-project.properties
src/app/ffbe/services/vision-cards.service.ts

Fixing item search by french name

---

src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-morale-jauge-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts

This handles the new ability to fill the Morale jauge.
Fixes #483

 #483: Added the AbilityMoraleJaugeEffect SkillEffect

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-morale-scaling-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-morale-scaling-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts
src/app/ffbe/model/skill.model.ts

Missing morale scaling damage parsing

---

src/app/ffbe/model/effects/abilities/ability-weapon-type-wielder-damage-increase-effect.model.ts

Fixing a wrong parameter error for a warning in weapon type wielder damage increase parsing

---

src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
src/app/ffbe/mappers/effects/passive-effect-parser.factory.ts
src/app/ffbe/model/effects/abilities/ability-elements-absorb-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/ability-elements-absorb-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts
src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-elements-absorb-effect.model.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts

Missing element absorb activation parsing

---

package.json
sonar-project.properties
src/app/ffbe/model/effects/passive-skill-effect.factory.ts
src/app/ffbe/model/effects/passives/passive-damages-absorption-effect.model.ts
src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts

This effect heals its caster when they inflict physical damages.
Fixes #484

 #484: Added the PassiveDamagesAbsorptionEffect

---

src/app/ffbe/model/effects/abilities/skill/ability-skill-multiple-activation-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/skill/ability-skill-multiple-activation-effect.model.ts
src/app/ffbe/model/effects/passives/skill/passive-skill-battle-start-activation-effect.model.ts

Fixing distinct skill multiple activation parsing.

---

src/app/ffbe/model/effects/abilities/skill/ability-skill-multiple-activation-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/skill/ability-skill-multiple-activation-effect.model.ts

Fixing number of uses restriction in multi-skill activation parsing

---

src/app/ffbe/services/vision-cards.service.ts

Fixing a crash when parsing Vision Cards having multiple skills at the same level

---

src/app/ffbe/mappers/character-entry-mapper.spec.ts
src/app/ffbe/mappers/character-entry-mapper.ts

Limit Bursts activated skills are now added to the unit activated skills list

---

src/php/recettes.php

The assumption has one only recipe produces a give item no longer holds.
Fixes #489

 #489: Recettes must now have a Gumi ID to be searched in DB

---

src/app/ffbe/mappers/character-entry-mapper.ts
src/app/ffbe/model/unite.model.ts

Fixes #514 
The UniteCompetenceArray was still undefined when loading the LB.

 #514: Fixed crash when loading Character with Skills activated by their LB

---

src/app/ffbe/model/effects/abilities/damage/ability-damage-magic-mp-increased-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-magic-mp-increased-effect.model.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-magic-mp-scaling-effect.model.spec.ts
src/app/ffbe/model/effects/abilities/damage/ability-damage-magic-mp-scaling-effect.model.ts
src/app/ffbe/model/effects/ability-skill-effect.factory.ts
src/app/ffbe/model/skill.model.ts

Damage abilities scaling on MP parsing.

---

.travis.yml
package.json
sonar-project.properties
src/app/ffbe/model/effects/passives/skill/passive-skill-counter-attack-activation-effect.model.spec.ts
src/app/ffbe/model/effects/passives/skill/passive-skill-counter-attack-activation-effect.model.ts

Fixes #528 
This rare case was not handled before.

 #528: Added counters with normal attacks in PassiveSkillCounterAttackActivationEffect

---

package.json
sonar-project.properties
src/app/ffbe/services/equipments.service.ts
src/app/ffbe/services/materias.service.ts
src/app/ffbe/services/vision-cards.service.ts

Fixing a crash when searching items having skills not present in data mining
