Wisdomb33r/ffch-admin

- src/app/ffbe/mappers/skill-mapper.ts
The method was designed for icons named "ability_xyz.png".
However global abilities are named "global_ability_xyz.png"
> Fixed the method transformIcon in the skill mapper

- src/app/ffbe/characters/characters.component.ts
- src/app/ffbe/enhancements/enhancements.component.ts
- src/app/ffbe/ffbe.constants.ts
- src/app/ffbe/services/characters.service.ts
Introduced the method "searchForCharacterByNameOrGumiId" in the Character Service.
If the input value has 9 digits and can be read as a number, the character service will search by Gumi ID, otherwise by name.
Used this method instead of "searchCharacterByName" in the Characters and the Enhancements components.
> Added the possibility to search for a character by gumi ID

- src/app/ffbe/mappers/effects/abilities/ability-stats-modification.parser.spec.ts
- src/app/ffbe/mappers/effects/abilities/ability-stats-modification.parser.ts
This effect can last for 0 turns, or until the target dies.
> #61: Fixed special durations for AbilityStatsModificationParser

- src/app/ffbe/mappers/effects/abilities/ability-element-resistances.parser.spec.ts
- src/app/ffbe/mappers/effects/abilities/ability-element-resistances.parser.ts
The sign was wrong when the effect decreased the resistance to all elements.
> Fixed sign in the AbilityElementResistancesParser

- src/app/ffbe/mappers/effects/abilities/ability-cooldown-parser.spec.ts
- src/app/ffbe/mappers/effects/abilities/ability-cooldown-parser.ts
Adapted the AbilityCooldownParser to handle cooldowns that trigger only once when dual-wielding.
Fixes #101
> Physical/Hybrid CD's without double DW activation

- src/app/ffbe/mappers/equipment-mapper.ts
- src/app/ffbe/model/objet/objet.model.ts
- src/app/ffbe/objet-display/objet-display.component.html
- src/php/classes.php
- src/php/objects.php
Fixes #98 :
Weapons can now have damage variance, even if they are one-handed.
> Fixed handling of weapon damage variance

- src/php/skill_awakenings.php
Fixes: #120: The bug where enhancements were wrongly added as latent abilities on lower levels
The PHP script now only add the base skill as a latent one if the enhancement consumes Enlightment Point(s).
> Fixed: Enhancements were wrongly added as latent abilities on lower levels

- src/app/ffbe/mappers/effects/passive-effect-parser.factory.spec.ts
- src/app/ffbe/mappers/effects/passives/passive-killer-damage-increase.parser.ts
> Fixing a wrong parsing of passive killer effects when applying the same value to several monster types

- src/app/ffbe/mappers/effects/abilities/ability-enemy-scan.parser.ts
> #212: Missing case in the AbilityEnemyScanParser

- src/app/ffbe/unit-awakening-materials-display/unit-awakening-materials-display.component.html
- src/app/ffbe/unit-awakening-materials-display/unit-awakening-materials-display.component.ts
The checkbox is now displayed only for 6* units.
> #216: Fixed display of Prism obtainment checkbox

- src/app/ffbe/mappers/effects/abilities/ability-skill-activation.parser.spec.ts
- src/app/ffbe/mappers/effects/abilities/ability-skill-activation.parser.ts
- src/app/ffbe/model/skill.model.spec.ts
Fixes #237 
Since these skills become available at the beginning of the turn, the turn computation had to be adjusted.
> #237: Fixed the number of turns for skills enabled at the start of battle

- src/php/units.php
The backend now expects Neo-Vision units to have CaracEX, and all other types of units to not have them.
Fixes #305
> #305: Fixed pushing of Brave Shift units

- src/app/ffbe/unit-awakening-materials-display/unit-awakening-materials-display.component.ts
- src/php/unit_awakenings.php
Fixes #315 
Added the possibility to store awakening materials for 7-stars units.
Changed the wording of the "obtaining" entry according to the GUI change in the game.
> #315: Updated handling of unit-specific awakening materials in the backend

- src/app/ffbe/mappers/skill-mapper.ts
- src/app/ffbe/model/effects/abilities/skill/ability-skill-magnus-glex-effect.model.spec.ts
- src/app/ffbe/model/effects/abilities/skill/ability-skill-magnus-glex-effect.model.ts
- src/app/ffbe/model/effects/ability-skill-effect.factory.ts
- src/app/ffbe/model/skill.model.spec.ts
The parser itself is straightforward, but the Magnus effect should appear first in the effect list, so that skill effects should be sorted.
> #348: Added parser for Magnus skills of GLEX units

- src/app/ffbe/model/effects/abilities/skill/ability-skill-magnus-effect.model.ts
The parameter 6 can be either 0 or 1.
Fixes #395
> #395: Fixed crash when loading new magnus skills

- src/app/ffbe/model/effects/abilities/skill/ability-skill-cooldown-effect.model.ts
- src/app/ffbe/model/effects/abilities/skill/ability-skill-magnus-effect.model.ts
- src/app/ffbe/model/effects/abilities/skill/ability-skill-switch-effect.model.ts
The method getDamagesPower() could crash if the activated skill could not be parsed.
Fixes #395
> #395: Fixed potential crash for skills with activated skill

- src/app/ffbe/model/effects/passives/passive-elements-resistance-effect.model.ts
- src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts
Pyro Glacial Lasswell has a Passive ElementsResistance SkillEffect with 7 parameters instead of 8 (for the elements).
Added a filler to the expected parameters so that there are always 8 of them.
Fixes #326
>  #326: Fixed wrong parameters in PassiveElementsResistanceParser

- src/app/ffbe/model/effects/passives/passive-skill-effects.spec.ts
- src/app/ffbe/model/effects/passives/stats/passive-stats-increase-fixed-effect.model.ts
The array can have less than 6 entries.
Fixes #445
>  #445: Fixed parameterError in PassiveStatsIncreaseFixedEffect

- src/php/skills.php
Skills with frames equal to '0' where considered as having no frames when storing them into DB.
Fixes #438 (Hopefully)
>  #438: Fixed repushing mismatch for skill frames

- src/app/ffbe/model/effects/passive-skill-effect.factory.ts
- src/app/ffbe/model/effects/passives/skill/passive-skill-morale-jauge-activation-effect.model.spec.ts
- src/app/ffbe/model/effects/passives/skill/passive-skill-morale-jauge-activation-effect.model.ts
This SkillEffect activates a Skill when the Morale Jauge is above or below a given threshold.
Fixes #488
>  #488: Added the PassiveSkillMoraleJaugeActivationEffect

- src/app/ffbe/services/characters.service.ts
The previous implementation only checked in the Character EX+1 awakening.
Fixes #516
>  #516: Fixed issue where Vision Cards were not linked to Personnage

- src/app/ffbe/mappers/character-entry-mapper.spec.ts
- src/app/ffbe/mappers/character-entry-mapper.ts
In this case, the (English) "name" field is used with a warning.
Fixes #533
>   #533: Fixed crash when LimitBurst had no names
